version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch-for-elasticsearch-app
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - es-network

  app:
    build: .
    container_name: elasticsearch-app
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
    networks:
      - es-network

volumes:
  es-data:

networks:
  es-network:
